### PR TITLE
Default MFA display function

### LINKED ISSUE #110: Detailed Type of Multifactor Authentication in User Information Tab similar to Dashboard
In Management Dashboard under User Details tab, there is detailed information about the MFA (e.g. for SMS it's masked phone number, authenticator, recovery code, etc).

In DAE User Information tab, it just shows an abstract multifactor type of "guardian".

dashboard-mfa
dae-v3-mfa

### PR DESCRIPTION
**Pull request by zxan1285**
# ✏️ Changes
Added a default display function for `Multifactor` field.

# 🔗 References
Fixes #110 
Jira: https://auth0team.atlassian.net/browse/KEY-222

# 🎯 Testing
✅ This has been tested locally
✅ This has been tested in a webtask
✅ This change has unit test coverage
✅ This change has been acceptance tested
✅ This change has been manually smoke tested

# 🚀 Deployment
🚫 This change can support multiple releases of the code serving traffic at the same time
✅ This can be deployed any time because it has no prerequisites.

# 🎡 Rollout

✅ The change will be available to the complete environment at once
🚫 The change is behind a feature flag and will go through a percentage based rollout process
🚫 The change is behind a flag and customers will opt-in to the change

In order to verify that the deployment was successful we will update the extensions via a test tenant and perform smoke tests to ensure proper execution.

# 🔥 Rollback
We will rollback if:

- the smoke test fails
- we receive a customer ticket indicating we broke the extension

## 📄 Procedure

A code revert+redeploy can be done to revert the change.

# 🖥 Appliance

✅ This change is compatible with the appliance.

### CODE REVIEW

**Comment by auth0extensions** [comment]
MD5: 441018525208457705bf09a8ee3c1093

# NSP - Security Report

_This is an automated security audit of this project. Please do not modify its contents_

Vulnerabilities found: **20**
Affected Modules: **hoek, hoek, hoek, hoek, superagent, superagent, superagent, mime, mime, mime, mime, mime, superagent, superagent, debug, fresh, lodash, lodash, safe-eval, superagent**
Summary:

- Prototype pollution attack
- Prototype pollution attack
- Prototype pollution attack
- Prototype pollution attack
- Large gzip Denial of Service
- Large gzip Denial of Service
- Large gzip Denial of Service
- Regular Expression Denial of Service
- Regular Expression Denial of Service
- Regular Expression Denial of Service
- Regular Expression Denial of Service
- Regular Expression Denial of Service
- Large gzip Denial of Service
- Large gzip Denial of Service
- Regular Expression Denial of Service
- Regular Expression Denial of Service
- Prototype Pollution
- Prototype Pollution
- Sandbox Breakout
- Large gzip Denial of Service


## Detailed report
#### Prototype pollution attack

Affected Module: **hoek**
Installed version: **2.16.3**
Patched versions: **> 4.2.0 < 5.0.0 || >= 5.0.3**
Advisory: https://nodesecurity.io/advisories/566
Path: **auth0-delegated-admin@3.1.0 > auth0-extension-express-tools@1.1.8 > webtask-tools@3.3.0 > boom@2.10.1 > hoek@2.16.3**

---

#### Prototype pollution attack

Affected Module: **hoek**
Installed version: **2.16.3**
Patched versions: **> 4.2.0 < 5.0.0 || >= 5.0.3**
Advisory: https://nodesecurity.io/advisories/566
Path: **auth0-delegated-admin@3.1.0 > auth0-extension-tools@1.3.3 > webtask-tools@3.3.0 > boom@2.10.1 > hoek@2.16.3**

---

#### Prototype pollution attack

Affected Module: **hoek**
Installed version: **2.16.3**
Patched versions: **> 4.2.0 < 5.0.0 || >= 5.0.3**
Advisory: https://nodesecurity.io/advisories/566
Path: **auth0-delegated-admin@3.1.0 > jsonwebtoken@7.4.3 > joi@6.10.1 > hoek@2.16.3**

---

#### Prototype pollution attack

Affected Module: **hoek**
Installed version: **2.16.3**
Patched versions: **> 4.2.0 < 5.0.0 || >= 5.0.3**
Advisory: https://nodesecurity.io/advisories/566
Path: **auth0-delegated-admin@3.1.0 > webtask-tools@3.3.0 > boom@2.10.1 > hoek@2.16.3**

---

#### Large gzip Denial of Service

Affected Module: **superagent**
Installed version: **1.8.5**
Patched versions: **>=3.7.0**
Advisory: https://nodesecurity.io/advisories/479
Path: **auth0-delegated-admin@3.1.0 > auth0-extension-express-tools@1.1.8 > webtask-tools@3.3.0 > superagent@1.8.5**

---

#### Large gzip Denial of Service

Affected Module: **superagent**
Installed version: **1.8.5**
Patched versions: **>=3.7.0**
Advisory: https://nodesecurity.io/advisories/479
Path: **auth0-delegated-admin@3.1.0 > auth0-extension-tools@1.3.3 > webtask-tools@3.3.0 > superagent@1.8.5**

---

#### Large gzip Denial of Service

Affected Module: **superagent**
Installed version: **1.8.5**
Patched versions: **>=3.7.0**
Advisory: https://nodesecurity.io/advisories/479
Path: **auth0-delegated-admin@3.1.0 > webtask-tools@3.3.0 > superagent@1.8.5**

---

#### Regular Expression Denial of Service

Affected Module: **mime**
Installed version: **1.3.4**
Patched versions: **>= 1.4.1 < 2.0.0 || >= 2.0.3**
Advisory: https://nodesecurity.io/advisories/535
Path: **auth0-delegated-admin@3.1.0 > auth0-extension-express-tools@1.1.8 > webtask-tools@3.3.0 > superagent@1.8.5 > mime@1.3.4**

---

#### Regular Expression Denial of Service

Affected Module: **mime**
Installed version: **1.3.4**
Patched versions: **>= 1.4.1 < 2.0.0 || >= 2.0.3**
Advisory: https://nodesecurity.io/advisories/535
Path: **auth0-delegated-admin@3.1.0 > auth0-extension-tools@1.3.3 > webtask-tools@3.3.0 > superagent@1.8.5 > mime@1.3.4**

---

#### Regular Expression Denial of Service

Affected Module: **mime**
Installed version: **1.3.4**
Patched versions: **>= 1.4.1 < 2.0.0 || >= 2.0.3**
Advisory: https://nodesecurity.io/advisories/535
Path: **auth0-delegated-admin@3.1.0 > express@4.14.0 > send@0.14.1 > mime@1.3.4**

---

#### Regular Expression Denial of Service

Affected Module: **mime**
Installed version: **1.3.4**
Patched versions: **>= 1.4.1 < 2.0.0 || >= 2.0.3**
Advisory: https://nodesecurity.io/advisories/535
Path: **auth0-delegated-admin@3.1.0 > superagent@1.2.0 > mime@1.3.4**

---

#### Regular Expression Denial of Service

Affected Module: **mime**
Installed version: **1.3.4**
Patched versions: **>= 1.4.1 < 2.0.0 || >= 2.0.3**
Advisory: https://nodesecurity.io/advisories/535
Path: **auth0-delegated-admin@3.1.0 > webtask-tools@3.3.0 > superagent@1.8.5 > mime@1.3.4**

---

#### Large gzip Denial of Service

Affected Module: **superagent**
Installed version: **2.3.0**
Patched versions: **>=3.7.0**
Advisory: https://nodesecurity.io/advisories/479
Path: **auth0-delegated-admin@3.1.0 > auth0-extension-express-tools@1.1.8 > auth0-extension-tools@1.3.3 > superagent@2.3.0**

---

#### Large gzip Denial of Service

Affected Module: **superagent**
Installed version: **2.3.0**
Patched versions: **>=3.7.0**
Advisory: https://nodesecurity.io/advisories/479
Path: **auth0-delegated-admin@3.1.0 > auth0-extension-tools@1.3.3 > superagent@2.3.0**

---

#### Regular Expression Denial of Service

Affected Module: **debug**
Installed version: **2.2.0**
Patched versions: **>= 2.6.9 < 3.0.0 || >= 3.1.0**
Advisory: https://nodesecurity.io/advisories/534
Path: **auth0-delegated-admin@3.1.0 > express@4.14.0 > debug@2.2.0**

---

#### Regular Expression Denial of Service

Affected Module: **fresh**
Installed version: **0.3.0**
Patched versions: **>= 0.5.2**
Advisory: https://nodesecurity.io/advisories/526
Path: **auth0-delegated-admin@3.1.0 > express@4.14.0 > fresh@0.3.0**

---

#### Prototype Pollution

Affected Module: **lodash**
Installed version: **3.10.1**
Patched versions: **>=4.17.5**
Advisory: https://nodesecurity.io/advisories/577
Path: **auth0-delegated-admin@3.1.0 > lodash@3.10.1**

---

#### Prototype Pollution

Affected Module: **lodash**
Installed version: **4.5.1**
Patched versions: **>=4.17.5**
Advisory: https://nodesecurity.io/advisories/577
Path: **auth0-delegated-admin@3.1.0 > lru-memoizer@1.10.0 > lodash@4.5.1**

---

#### Sandbox Breakout

Affected Module: **safe-eval**
Installed version: **0.3.0**
Patched versions: **<0.0.0**
Advisory: https://nodesecurity.io/advisories/337
Path: **auth0-delegated-admin@3.1.0 > safe-eval@0.3.0**

---

#### Large gzip Denial of Service

Affected Module: **superagent**
Installed version: **1.2.0**
Patched versions: **>=3.7.0**
Advisory: https://nodesecurity.io/advisories/479
Path: **auth0-delegated-admin@3.1.0 > superagent@1.2.0**

---

**Comment by goduncan** [comment]
@zxan1285 could you ping someone in the Product Security team about the issues identified above cc @MarcinHoppe

**Comment by zxan1285** [comment]
@goduncan we're working on fixing those vulnerabilities in separate PR (#112)

**Comment by MarcinHoppe** [comment]
@goduncan We have identified those a good while ago in a Snyk scan.

**Pull request merged**
