### PR TITLE
added new log types, fixed unknown logtype message

### PR DESCRIPTION
**Pull request by zxan1285**

### CODE REVIEW

**Comment by Verlic** [comment]
MD5: 93b885adfe0da089cdf634904fd59f71

# NSP - Security Report

_This is an automated security audit of this project. Please do not modify its contents_

Vulnerabilities found: **1**
Affected Modules: **safe-eval**
Summary:

- Sandbox Breakout


## Detailed report
#### Sandbox Breakout

Affected Module: **safe-eval**
Installed version: **0.3.0**
Patched versions: **<0.0.0**
Advisory: https://nodesecurity.io/advisories/337
Path: **auth0-delegated-admin@2.4.6 > safe-eval@0.3.0**

---

**Comment by sgmeyer** [comment]
LGTM

**Comment by sgmeyer** [comment]
@dctoon one more set of eyes?  Can you mark this as reviewed if you think it is legit.  Pretty straight forward PR.

**Comment by dctoon** [comment]
LGTM.

**Pull request merged**
